import assert from "node:assert/strict";
import test from "node:test";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { createWriterVerification } from "../packages/direct-agent/writer-verification.mjs";

test("clone verification runs real argv gates and binds the result without raw output", async (t) => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), "omp-writer-gates-"));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const project = path.join(root, "project");
  const clone = path.join(root, "clone");
  await fs.mkdir(path.join(project, ".pi"), { recursive: true });
  const manifest = { $schema: "project-gates-v1.schema.json", formatVersion: 1, id: "test", gates: [{ id: "unit", description: "Run signed-addition test", command: "node", args: ["test.mjs"], cwd: ".", timeoutSeconds: 5, env: {} }] };
  await fs.writeFile(path.join(project, ".pi/only-my-pi-gates.json"), JSON.stringify(manifest));
  await fs.writeFile(path.join(project, "math.mjs"), "export const add = (a,b) => a+b;\n");
  await fs.writeFile(path.join(project, "test.mjs"), "import {add} from './math.mjs'; console.log('PRIVATE_TEST_OUTPUT'); process.exit(add(-2,-3) === -5 ? 0 : 1);\n");
  const git = (...args) => execFileSync("git", args, { cwd: project, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  git("init"); git("add", "."); git("-c", "user.name=Fixture", "-c", "user.email=fixture@example.invalid", "commit", "-m", "baseline");
  git("clone", "--no-local", project, clone);
  let approved = true;
  let confirms = 0;
  const ctx = { cwd: project, mode: "tui", isProjectTrusted: () => true, sessionManager: { getSessionId: () => "test-session" }, ui: { async confirm(_title, description) { confirms++; assert.match(description, /NOT a filesystem/u); return approved; } } };
  const verify = createWriterVerification({ configRoot: root, getContext: () => ctx });
  const input = { cloneRoot: clone, patch: { sha256: `sha256:${"a".repeat(64)}`, baseCommit: git("rev-parse", "HEAD") }, requestedVerification: ["node test.mjs"] };
  const passed = await verify(input);
  assert.equal(passed.status, "PASS");
  assert.equal(passed.results[0].exitCode, 0);
  assert.equal(passed.patchDigest, input.patch.sha256);
  assert.ok(!JSON.stringify(passed).includes("PRIVATE_TEST_OUTPUT"));
  assert.ok(!JSON.stringify(passed).includes(root));
  await fs.writeFile(path.join(clone, "math.mjs"), "export const add = (a,b) => Math.abs(a+b);\n");
  const failed = await verify(input);
  assert.equal(failed.status, "FAIL"); assert.equal(failed.results[0].exitCode, 1);
  approved = false;
  assert.equal((await verify(input)).code, "WRITER_GATE_DENIED");
  approved = true;
  const signal = AbortSignal.abort();
  assert.equal((await verify({ ...input, signal })).code, "WRITER_GATE_CANCELLED");
  manifest.gates[0].args = ["different.mjs"];
  await fs.writeFile(path.join(clone, ".pi/only-my-pi-gates.json"), JSON.stringify(manifest));
  const before = confirms;
  assert.equal((await verify(input)).code, "WRITER_GATE_MANIFEST_DRIFT"); assert.equal(confirms, before);
  await fs.rm(path.join(clone, ".pi/only-my-pi-gates.json"));
  assert.equal((await verify(input)).code, "WRITER_GATE_MANIFEST_REQUIRED");
  ctx.mode = "print";
  assert.equal((await verify(input)).code, "WRITER_GATE_TRUST_REQUIRED");
});
